In [1]:
import numpy as np 
import seaborn as sns 
import pandas as pd 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [2]:
df =pd.read_csv(r"C:\Users\sheeshragar\Downloads\IRIS.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(df['species'])

LabelEncoder()

In [5]:
df['species']=le.transform(df['species'])

In [6]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [7]:
x= df.drop(columns='species')
y=df['species']
x,y

(     sepal_length  sepal_width  petal_length  petal_width
 0             5.1          3.5           1.4          0.2
 1             4.9          3.0           1.4          0.2
 2             4.7          3.2           1.3          0.2
 3             4.6          3.1           1.5          0.2
 4             5.0          3.6           1.4          0.2
 ..            ...          ...           ...          ...
 145           6.7          3.0           5.2          2.3
 146           6.3          2.5           5.0          1.9
 147           6.5          3.0           5.2          2.0
 148           6.2          3.4           5.4          2.3
 149           5.9          3.0           5.1          1.8
 
 [150 rows x 4 columns],
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 145    2
 146    2
 147    2
 148    2
 149    2
 Name: species, Length: 150, dtype: int32)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x= scaler.fit_transform(x)

In [17]:
x,y

(array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
         -1.31297673e+00],
        [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
         -1.31297673e+00],
        [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
         -1.31297673e+00],
        [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
         -1.31297673e+00],
        [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
         -1.31297673e+00],
        [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
         -1.05003079e+00],
        [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
         -1.18150376e+00],
        [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
         -1.31297673e+00],
        [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
         -1.31297673e+00],
        [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
         -1.44444970e+00],
        [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
         -1.31297673e+00],
        [-1.26418478e+00,  8.00654259e-01, 

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [21]:
x_train.shape,x_test.shape

((100, 4), (50, 4))

In [23]:
from sklearn.linear_model import Perceptron

ps = Perceptron()
ps.fit(x_train,y_train)

Perceptron()

In [25]:
ps.score(x_train,y_train),ps.score(x_test,y_test)

(0.94, 0.92)

In [27]:
pred_y=ps.predict(x_test)

In [29]:
# from mlxtend.plotting import plot_decision_regions
# plot_decision_regions(x_train.to_numpy(),y_train.to_numpy(),clf=ps)

In [71]:
import tensorflow

from keras.layers import Dense,Dropout,BatchNormalization
from keras.models import Sequential

In [32]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [33]:
ann =Sequential()

In [93]:
ann.add(Dense(18, input_dim =4, activation='relu')),
ann.add(BatchNormalization())
ann.add(Dense(12,  activation='relu'))
ann.add(BatchNormalization())


ann.add(Dense(9,  activation='relu'))
ann.add(BatchNormalization())


ann.add(Dense(6,  activation='relu'))
ann.add(BatchNormalization())


ann.add(Dense(3,  activation='softmax'))

In [94]:
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [36]:
# from tensorflow.keras.utils import to_categorical

# y_train_cat = to_categorical(y_train)
# y_test_cat = to_categorical(y_test)

# # Now train with the categorical labels
# ann.fit(x_train, y_train_cat, batch_size=20, epochs=20)


In [105]:
x_train.shape

(100, 4)

In [53]:
from keras.callbacks import EarlyStopping

In [97]:
ann.fit(x_train,y_train,batch_size=10,epochs=30,validation_split=0.2)

Epoch 1/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 12s 120ms/step - accuracy: 0.7750 - loss: 0.6246 - val_accuracy: 0.4500 - val_loss: 1.0933
Epoch 2/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8250 - loss: 0.4969 - val_accuracy: 0.8500 - val_loss: 1.0620
Epoch 3/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7875 - loss: 0.5706 - val_accuracy: 0.7500 - val_loss: 1.0300
Epoch 4/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8250 - loss: 0.4800 - val_accuracy: 0.7000 - val_loss: 1.0060
Epoch 5/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8750 - loss: 0.4317 - val_accuracy: 0.7000 - val_loss: 0.9787
Epoch 6/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8750 - loss: 0.4299 - val_accuracy: 0.7000 - val_loss: 0.9582
Epoch 7/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9125 - loss: 0.3283 - val_accuracy: 0.7000 - val_loss: 0.9476
Epoch 8/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7625 - loss: 0.5988 - val_accuracy: 0.7000 - val_loss: 0.939

In [100]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test,y_pred), accuracy_score (y_train,y_pred2)

(0.8, 0.83)

In [98]:
y_pred_prob = ann.predict(x_test)         # probabilities for each class
y_pred = np.argmax(y_pred_prob, axis=1) 
y_pred

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 392ms/step


array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [99]:
y_pred_prob = ann.predict(x_train)         # probabilities for each class
y_pred2 = np.argmax(y_pred_prob, axis=1) 
y_pred2

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([1, 2, 2, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0,
       2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2,
       2, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 1, 2, 0, 2, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 0, 2, 1, 0, 1, 2], dtype=int64)

In [69]:
ann.history.history

{'accuracy': [0.875,
  0.8374999761581421,
  0.8374999761581421,
  0.800000011920929,
  0.824999988079071],
 'loss': [0.3220953345298767,
  0.32871466875076294,
  0.32249516248703003,
  0.318742036819458,
  0.2836027145385742],
 'val_accuracy': [0.8500000238418579,
  0.8500000238418579,
  0.8500000238418579,
  0.8500000238418579,
  0.8500000238418579],
 'val_loss': [0.4558858871459961,
  0.4465347230434418,
  0.437567800283432,
  0.42995843291282654,
  0.43441516160964966]}